// flow-typed signature: 9eda176981bc25a528450b30a9c4d7f3
// flow-typed version: <<STUB>>/alpha2-countries_v^1.1.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'alpha2-countries'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'alpha2-countries' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'alpha2-countries/dist/bundle' {
  declare module.exports: any;
}

declare module 'alpha2-countries/src/index' {
  declare module.exports: any;
}

declare module 'alpha2-countries/webpack.bundle.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'alpha2-countries/dist/bundle.js' {
  declare module.exports: $Exports<'alpha2-countries/dist/bundle'>;
}
declare module 'alpha2-countries/src/index.js' {
  declare module.exports: $Exports<'alpha2-countries/src/index'>;
}
declare module 'alpha2-countries/webpack.bundle.config.js' {
  declare module.exports: $Exports<'alpha2-countries/webpack.bundle.config'>;
}
