// flow-typed signature: 099aab198b38e7bd4d444a12e98dd097
// flow-typed version: <<STUB>>/bootstrap-material-design_v^4.0.0-beta.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-material-design'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-material-design' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-material-design/dist/js/bootstrap-material-design' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/dist/js/bootstrap-material-design.min' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/autofill' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/base' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/baseFormControl' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/baseInput' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/baseLayout' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/baseSelection' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/bootstrapMaterialDesign' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/checkbox' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/checkboxInline' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/collapseInline' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/drawer' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/file' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/index' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/radio' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/radioInline' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/ripples' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/select' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/switch' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/text' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/textarea' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/js/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-material-design/dist/js/bootstrap-material-design.js' {
  declare module.exports: $Exports<'bootstrap-material-design/dist/js/bootstrap-material-design'>;
}
declare module 'bootstrap-material-design/dist/js/bootstrap-material-design.min.js' {
  declare module.exports: $Exports<'bootstrap-material-design/dist/js/bootstrap-material-design.min'>;
}
declare module 'bootstrap-material-design/js/autofill.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/autofill'>;
}
declare module 'bootstrap-material-design/js/base.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/base'>;
}
declare module 'bootstrap-material-design/js/baseFormControl.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/baseFormControl'>;
}
declare module 'bootstrap-material-design/js/baseInput.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/baseInput'>;
}
declare module 'bootstrap-material-design/js/baseLayout.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/baseLayout'>;
}
declare module 'bootstrap-material-design/js/baseSelection.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/baseSelection'>;
}
declare module 'bootstrap-material-design/js/bootstrapMaterialDesign.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/bootstrapMaterialDesign'>;
}
declare module 'bootstrap-material-design/js/checkbox.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/checkbox'>;
}
declare module 'bootstrap-material-design/js/checkboxInline.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/checkboxInline'>;
}
declare module 'bootstrap-material-design/js/collapseInline.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/collapseInline'>;
}
declare module 'bootstrap-material-design/js/drawer.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/drawer'>;
}
declare module 'bootstrap-material-design/js/file.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/file'>;
}
declare module 'bootstrap-material-design/js/index.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/index'>;
}
declare module 'bootstrap-material-design/js/radio.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/radio'>;
}
declare module 'bootstrap-material-design/js/radioInline.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/radioInline'>;
}
declare module 'bootstrap-material-design/js/ripples.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/ripples'>;
}
declare module 'bootstrap-material-design/js/select.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/select'>;
}
declare module 'bootstrap-material-design/js/switch.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/switch'>;
}
declare module 'bootstrap-material-design/js/text.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/text'>;
}
declare module 'bootstrap-material-design/js/textarea.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/textarea'>;
}
declare module 'bootstrap-material-design/js/util.js' {
  declare module.exports: $Exports<'bootstrap-material-design/js/util'>;
}
