// flow-typed signature: 701e3cc6a74ce7dcb1281d4d255bd2f6
// flow-typed version: <<STUB>>/bs58check_v^2.0.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs58check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs58check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'bs58check/index' {
  declare module.exports: $Exports<'bs58check'>;
}
declare module 'bs58check/index.js' {
  declare module.exports: $Exports<'bs58check'>;
}
