// flow-typed signature: 07f7269b41c168753bcbbd9be80f44df
// flow-typed version: <<STUB>>/change-bootstrap_vChangeFinance/change-bootstrap/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'change-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'change-bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'change-bootstrap/assets/js/docs.min' {
  declare module.exports: any;
}

declare module 'change-bootstrap/assets/js/ie-emulation-modes-warning' {
  declare module.exports: any;
}

declare module 'change-bootstrap/assets/js/ie10-viewport-bug-workaround' {
  declare module.exports: any;
}

declare module 'change-bootstrap/assets/js/src/application' {
  declare module.exports: any;
}

declare module 'change-bootstrap/assets/js/vendor/anchor.min' {
  declare module.exports: any;
}

declare module 'change-bootstrap/assets/js/vendor/clipboard.min' {
  declare module.exports: any;
}

declare module 'change-bootstrap/assets/js/vendor/holder.min' {
  declare module.exports: any;
}

declare module 'change-bootstrap/assets/js/vendor/jquery-slim.min' {
  declare module.exports: any;
}

declare module 'change-bootstrap/assets/js/vendor/popper.min' {
  declare module.exports: any;
}

declare module 'change-bootstrap/assets/js/vendor/split.min' {
  declare module.exports: any;
}

declare module 'change-bootstrap/dist/js/bootstrap-material-design' {
  declare module.exports: any;
}

declare module 'change-bootstrap/dist/js/bootstrap-material-design.min' {
  declare module.exports: any;
}

declare module 'change-bootstrap/docs/4.0/examples/offcanvas/offcanvas' {
  declare module.exports: any;
}

declare module 'change-bootstrap/docs/4.0/examples/tooltip-viewport/tooltip-viewport' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/autofill' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/base' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/baseFormControl' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/baseInput' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/baseLayout' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/baseSelection' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/bootstrapMaterialDesign' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/checkbox' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/checkboxInline' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/collapseInline' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/drawer' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/dropdown' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/file' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/index' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/radio' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/radioInline' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/ripples' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/select' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/switch' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/text' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/textarea' {
  declare module.exports: any;
}

declare module 'change-bootstrap/js/util' {
  declare module.exports: any;
}

declare module 'change-bootstrap/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'change-bootstrap/assets/js/docs.min.js' {
  declare module.exports: $Exports<'change-bootstrap/assets/js/docs.min'>;
}
declare module 'change-bootstrap/assets/js/ie-emulation-modes-warning.js' {
  declare module.exports: $Exports<'change-bootstrap/assets/js/ie-emulation-modes-warning'>;
}
declare module 'change-bootstrap/assets/js/ie10-viewport-bug-workaround.js' {
  declare module.exports: $Exports<'change-bootstrap/assets/js/ie10-viewport-bug-workaround'>;
}
declare module 'change-bootstrap/assets/js/src/application.js' {
  declare module.exports: $Exports<'change-bootstrap/assets/js/src/application'>;
}
declare module 'change-bootstrap/assets/js/vendor/anchor.min.js' {
  declare module.exports: $Exports<'change-bootstrap/assets/js/vendor/anchor.min'>;
}
declare module 'change-bootstrap/assets/js/vendor/clipboard.min.js' {
  declare module.exports: $Exports<'change-bootstrap/assets/js/vendor/clipboard.min'>;
}
declare module 'change-bootstrap/assets/js/vendor/holder.min.js' {
  declare module.exports: $Exports<'change-bootstrap/assets/js/vendor/holder.min'>;
}
declare module 'change-bootstrap/assets/js/vendor/jquery-slim.min.js' {
  declare module.exports: $Exports<'change-bootstrap/assets/js/vendor/jquery-slim.min'>;
}
declare module 'change-bootstrap/assets/js/vendor/popper.min.js' {
  declare module.exports: $Exports<'change-bootstrap/assets/js/vendor/popper.min'>;
}
declare module 'change-bootstrap/assets/js/vendor/split.min.js' {
  declare module.exports: $Exports<'change-bootstrap/assets/js/vendor/split.min'>;
}
declare module 'change-bootstrap/dist/js/bootstrap-material-design.js' {
  declare module.exports: $Exports<'change-bootstrap/dist/js/bootstrap-material-design'>;
}
declare module 'change-bootstrap/dist/js/bootstrap-material-design.min.js' {
  declare module.exports: $Exports<'change-bootstrap/dist/js/bootstrap-material-design.min'>;
}
declare module 'change-bootstrap/docs/4.0/examples/offcanvas/offcanvas.js' {
  declare module.exports: $Exports<'change-bootstrap/docs/4.0/examples/offcanvas/offcanvas'>;
}
declare module 'change-bootstrap/docs/4.0/examples/tooltip-viewport/tooltip-viewport.js' {
  declare module.exports: $Exports<'change-bootstrap/docs/4.0/examples/tooltip-viewport/tooltip-viewport'>;
}
declare module 'change-bootstrap/js/autofill.js' {
  declare module.exports: $Exports<'change-bootstrap/js/autofill'>;
}
declare module 'change-bootstrap/js/base.js' {
  declare module.exports: $Exports<'change-bootstrap/js/base'>;
}
declare module 'change-bootstrap/js/baseFormControl.js' {
  declare module.exports: $Exports<'change-bootstrap/js/baseFormControl'>;
}
declare module 'change-bootstrap/js/baseInput.js' {
  declare module.exports: $Exports<'change-bootstrap/js/baseInput'>;
}
declare module 'change-bootstrap/js/baseLayout.js' {
  declare module.exports: $Exports<'change-bootstrap/js/baseLayout'>;
}
declare module 'change-bootstrap/js/baseSelection.js' {
  declare module.exports: $Exports<'change-bootstrap/js/baseSelection'>;
}
declare module 'change-bootstrap/js/bootstrapMaterialDesign.js' {
  declare module.exports: $Exports<'change-bootstrap/js/bootstrapMaterialDesign'>;
}
declare module 'change-bootstrap/js/checkbox.js' {
  declare module.exports: $Exports<'change-bootstrap/js/checkbox'>;
}
declare module 'change-bootstrap/js/checkboxInline.js' {
  declare module.exports: $Exports<'change-bootstrap/js/checkboxInline'>;
}
declare module 'change-bootstrap/js/collapseInline.js' {
  declare module.exports: $Exports<'change-bootstrap/js/collapseInline'>;
}
declare module 'change-bootstrap/js/drawer.js' {
  declare module.exports: $Exports<'change-bootstrap/js/drawer'>;
}
declare module 'change-bootstrap/js/dropdown.js' {
  declare module.exports: $Exports<'change-bootstrap/js/dropdown'>;
}
declare module 'change-bootstrap/js/file.js' {
  declare module.exports: $Exports<'change-bootstrap/js/file'>;
}
declare module 'change-bootstrap/js/index.js' {
  declare module.exports: $Exports<'change-bootstrap/js/index'>;
}
declare module 'change-bootstrap/js/radio.js' {
  declare module.exports: $Exports<'change-bootstrap/js/radio'>;
}
declare module 'change-bootstrap/js/radioInline.js' {
  declare module.exports: $Exports<'change-bootstrap/js/radioInline'>;
}
declare module 'change-bootstrap/js/ripples.js' {
  declare module.exports: $Exports<'change-bootstrap/js/ripples'>;
}
declare module 'change-bootstrap/js/select.js' {
  declare module.exports: $Exports<'change-bootstrap/js/select'>;
}
declare module 'change-bootstrap/js/switch.js' {
  declare module.exports: $Exports<'change-bootstrap/js/switch'>;
}
declare module 'change-bootstrap/js/text.js' {
  declare module.exports: $Exports<'change-bootstrap/js/text'>;
}
declare module 'change-bootstrap/js/textarea.js' {
  declare module.exports: $Exports<'change-bootstrap/js/textarea'>;
}
declare module 'change-bootstrap/js/util.js' {
  declare module.exports: $Exports<'change-bootstrap/js/util'>;
}
declare module 'change-bootstrap/rollup.config.js' {
  declare module.exports: $Exports<'change-bootstrap/rollup.config'>;
}
