// flow-typed signature: 2fc0045155549cad13938d941dfe9821
// flow-typed version: <<STUB>>/flag_v^3.0.0-0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flag/build/connected-flags-provider' {
  declare module.exports: any;
}

declare module 'flag/build/create-flags-reducer' {
  declare module.exports: any;
}

declare module 'flag/build/flag' {
  declare module.exports: any;
}

declare module 'flag/build/flags-provider' {
  declare module.exports: any;
}

declare module 'flag/build/index' {
  declare module.exports: any;
}

declare module 'flag/build/key' {
  declare module.exports: any;
}

declare module 'flag/build/set-flags-action' {
  declare module.exports: any;
}

declare module 'flag/build/types' {
  declare module.exports: any;
}

declare module 'flag/build/with-flags' {
  declare module.exports: any;
}

declare module 'flag/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flag/build/connected-flags-provider.js' {
  declare module.exports: $Exports<'flag/build/connected-flags-provider'>;
}
declare module 'flag/build/create-flags-reducer.js' {
  declare module.exports: $Exports<'flag/build/create-flags-reducer'>;
}
declare module 'flag/build/flag.js' {
  declare module.exports: $Exports<'flag/build/flag'>;
}
declare module 'flag/build/flags-provider.js' {
  declare module.exports: $Exports<'flag/build/flags-provider'>;
}
declare module 'flag/build/index.js' {
  declare module.exports: $Exports<'flag/build/index'>;
}
declare module 'flag/build/key.js' {
  declare module.exports: $Exports<'flag/build/key'>;
}
declare module 'flag/build/set-flags-action.js' {
  declare module.exports: $Exports<'flag/build/set-flags-action'>;
}
declare module 'flag/build/types.js' {
  declare module.exports: $Exports<'flag/build/types'>;
}
declare module 'flag/build/with-flags.js' {
  declare module.exports: $Exports<'flag/build/with-flags'>;
}
declare module 'flag/test/setup.js' {
  declare module.exports: $Exports<'flag/test/setup'>;
}
