// flow-typed signature: 0157b1c8e8b34d4e708c7bde547e4aa0
// flow-typed version: <<STUB>>/jspolyfill-array.prototype.findIndex_v^0.1.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jspolyfill-array.prototype.findIndex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jspolyfill-array.prototype.findIndex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jspolyfill-array.prototype.findIndex/findIndex' {
  declare module.exports: any;
}

declare module 'jspolyfill-array.prototype.findIndex/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jspolyfill-array.prototype.findIndex/findIndex.js' {
  declare module.exports: $Exports<'jspolyfill-array.prototype.findIndex/findIndex'>;
}
declare module 'jspolyfill-array.prototype.findIndex/test.js' {
  declare module.exports: $Exports<'jspolyfill-array.prototype.findIndex/test'>;
}
