// flow-typed signature: 616d90276abadf758fad836f5c8484d5
// flow-typed version: <<STUB>>/jspolyfill-array.prototype.find_v^0.1.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jspolyfill-array.prototype.find'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jspolyfill-array.prototype.find' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jspolyfill-array.prototype.find/find' {
  declare module.exports: any;
}

declare module 'jspolyfill-array.prototype.find/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jspolyfill-array.prototype.find/find.js' {
  declare module.exports: $Exports<'jspolyfill-array.prototype.find/find'>;
}
declare module 'jspolyfill-array.prototype.find/test.js' {
  declare module.exports: $Exports<'jspolyfill-array.prototype.find/test'>;
}
