// flow-typed signature: cbddec314b8c3dda4ca605ced74e67e1
// flow-typed version: <<STUB>>/moment-es6_v^1.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-es6'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment-es6' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'moment-es6/index' {
  declare module.exports: $Exports<'moment-es6'>;
}
declare module 'moment-es6/index.js' {
  declare module.exports: $Exports<'moment-es6'>;
}
