// flow-typed signature: b9df0ba754df45cbc06b47d48bdc5fad
// flow-typed version: <<STUB>>/react-mixpanel_v^0.0.9/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mixpanel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mixpanel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-mixpanel/lib/components/MixpanelProvider' {
  declare module.exports: any;
}

declare module 'react-mixpanel/lib/index' {
  declare module.exports: any;
}

declare module 'react-mixpanel/lib/utils/mixpanelShape' {
  declare module.exports: any;
}

declare module 'react-mixpanel/src/components/MixpanelProvider' {
  declare module.exports: any;
}

declare module 'react-mixpanel/src/index' {
  declare module.exports: any;
}

declare module 'react-mixpanel/src/utils/mixpanelShape' {
  declare module.exports: any;
}

declare module 'react-mixpanel/test/components/MixpanelProvider.spec' {
  declare module.exports: any;
}

declare module 'react-mixpanel/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-mixpanel/lib/components/MixpanelProvider.js' {
  declare module.exports: $Exports<'react-mixpanel/lib/components/MixpanelProvider'>;
}
declare module 'react-mixpanel/lib/index.js' {
  declare module.exports: $Exports<'react-mixpanel/lib/index'>;
}
declare module 'react-mixpanel/lib/utils/mixpanelShape.js' {
  declare module.exports: $Exports<'react-mixpanel/lib/utils/mixpanelShape'>;
}
declare module 'react-mixpanel/src/components/MixpanelProvider.js' {
  declare module.exports: $Exports<'react-mixpanel/src/components/MixpanelProvider'>;
}
declare module 'react-mixpanel/src/index.js' {
  declare module.exports: $Exports<'react-mixpanel/src/index'>;
}
declare module 'react-mixpanel/src/utils/mixpanelShape.js' {
  declare module.exports: $Exports<'react-mixpanel/src/utils/mixpanelShape'>;
}
declare module 'react-mixpanel/test/components/MixpanelProvider.spec.js' {
  declare module.exports: $Exports<'react-mixpanel/test/components/MixpanelProvider.spec'>;
}
declare module 'react-mixpanel/test/setup.js' {
  declare module.exports: $Exports<'react-mixpanel/test/setup'>;
}
