// flow-typed signature: a02a9eef61e564451c36fe474c9efdc4
// flow-typed version: <<STUB>>/react-global-configuration_v^1.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-global-configuration'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-global-configuration' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-global-configuration/build/configuration' {
  declare module.exports: any;
}

declare module 'react-global-configuration/build/index' {
  declare module.exports: any;
}

declare module 'react-global-configuration/build/reset' {
  declare module.exports: any;
}

declare module 'react-global-configuration/gulp/build' {
  declare module.exports: any;
}

declare module 'react-global-configuration/gulp/lint' {
  declare module.exports: any;
}

declare module 'react-global-configuration/gulp/test' {
  declare module.exports: any;
}

declare module 'react-global-configuration/gulpfile' {
  declare module.exports: any;
}

declare module 'react-global-configuration/lib/configuration' {
  declare module.exports: any;
}

declare module 'react-global-configuration/lib/index' {
  declare module.exports: any;
}

declare module 'react-global-configuration/lib/reset' {
  declare module.exports: any;
}

declare module 'react-global-configuration/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-global-configuration/build/configuration.js' {
  declare module.exports: $Exports<'react-global-configuration/build/configuration'>;
}
declare module 'react-global-configuration/build/index.js' {
  declare module.exports: $Exports<'react-global-configuration/build/index'>;
}
declare module 'react-global-configuration/build/reset.js' {
  declare module.exports: $Exports<'react-global-configuration/build/reset'>;
}
declare module 'react-global-configuration/gulp/build.js' {
  declare module.exports: $Exports<'react-global-configuration/gulp/build'>;
}
declare module 'react-global-configuration/gulp/lint.js' {
  declare module.exports: $Exports<'react-global-configuration/gulp/lint'>;
}
declare module 'react-global-configuration/gulp/test.js' {
  declare module.exports: $Exports<'react-global-configuration/gulp/test'>;
}
declare module 'react-global-configuration/gulpfile.js' {
  declare module.exports: $Exports<'react-global-configuration/gulpfile'>;
}
declare module 'react-global-configuration/lib/configuration.js' {
  declare module.exports: $Exports<'react-global-configuration/lib/configuration'>;
}
declare module 'react-global-configuration/lib/index.js' {
  declare module.exports: $Exports<'react-global-configuration/lib/index'>;
}
declare module 'react-global-configuration/lib/reset.js' {
  declare module.exports: $Exports<'react-global-configuration/lib/reset'>;
}
declare module 'react-global-configuration/test/index.test.js' {
  declare module.exports: $Exports<'react-global-configuration/test/index.test'>;
}
