// flow-typed signature: 2d4d7109a80667ba70bcabee582ad652
// flow-typed version: <<STUB>>/react-google-places-suggest_v^3.2.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-places-suggest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-places-suggest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-places-suggest/es/components/List/index' {
  declare module.exports: any;
}

declare module 'react-google-places-suggest/es/components/ListItem/index' {
  declare module.exports: any;
}

declare module 'react-google-places-suggest/es/components/Prediction/index' {
  declare module.exports: any;
}

declare module 'react-google-places-suggest/es/index' {
  declare module.exports: any;
}

declare module 'react-google-places-suggest/lib/components/List/index' {
  declare module.exports: any;
}

declare module 'react-google-places-suggest/lib/components/ListItem/index' {
  declare module.exports: any;
}

declare module 'react-google-places-suggest/lib/components/Prediction/index' {
  declare module.exports: any;
}

declare module 'react-google-places-suggest/lib/index' {
  declare module.exports: any;
}

declare module 'react-google-places-suggest/umd/react-google-places-suggest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-places-suggest/es/components/List/index.js' {
  declare module.exports: $Exports<'react-google-places-suggest/es/components/List/index'>;
}
declare module 'react-google-places-suggest/es/components/ListItem/index.js' {
  declare module.exports: $Exports<'react-google-places-suggest/es/components/ListItem/index'>;
}
declare module 'react-google-places-suggest/es/components/Prediction/index.js' {
  declare module.exports: $Exports<'react-google-places-suggest/es/components/Prediction/index'>;
}
declare module 'react-google-places-suggest/es/index.js' {
  declare module.exports: $Exports<'react-google-places-suggest/es/index'>;
}
declare module 'react-google-places-suggest/lib/components/List/index.js' {
  declare module.exports: $Exports<'react-google-places-suggest/lib/components/List/index'>;
}
declare module 'react-google-places-suggest/lib/components/ListItem/index.js' {
  declare module.exports: $Exports<'react-google-places-suggest/lib/components/ListItem/index'>;
}
declare module 'react-google-places-suggest/lib/components/Prediction/index.js' {
  declare module.exports: $Exports<'react-google-places-suggest/lib/components/Prediction/index'>;
}
declare module 'react-google-places-suggest/lib/index.js' {
  declare module.exports: $Exports<'react-google-places-suggest/lib/index'>;
}
declare module 'react-google-places-suggest/umd/react-google-places-suggest.js' {
  declare module.exports: $Exports<'react-google-places-suggest/umd/react-google-places-suggest'>;
}
