// flow-typed signature: 13bc71c58408dfa6649b462a860b7516
// flow-typed version: <<STUB>>/react-google-tag-manager_v^2.2.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-tag-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-tag-manager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-tag-manager/lib/build_parts' {
  declare module.exports: any;
}

declare module 'react-google-tag-manager/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-tag-manager/lib/build_parts.js' {
  declare module.exports: $Exports<'react-google-tag-manager/lib/build_parts'>;
}
declare module 'react-google-tag-manager/lib/index.js' {
  declare module.exports: $Exports<'react-google-tag-manager/lib/index'>;
}
