// flow-typed signature: 39af2e123a371cd5db6e9d7b2f9d5e91
// flow-typed version: <<STUB>>/react-google-maps-loader_v^4.1.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-maps-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-maps-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-maps-loader/es/index' {
  declare module.exports: any;
}

declare module 'react-google-maps-loader/es/loadGoogleMapsSdk/index' {
  declare module.exports: any;
}

declare module 'react-google-maps-loader/lib/index' {
  declare module.exports: any;
}

declare module 'react-google-maps-loader/lib/loadGoogleMapsSdk/index' {
  declare module.exports: any;
}

declare module 'react-google-maps-loader/umd/react-google-maps-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-maps-loader/es/index.js' {
  declare module.exports: $Exports<'react-google-maps-loader/es/index'>;
}
declare module 'react-google-maps-loader/es/loadGoogleMapsSdk/index.js' {
  declare module.exports: $Exports<'react-google-maps-loader/es/loadGoogleMapsSdk/index'>;
}
declare module 'react-google-maps-loader/lib/index.js' {
  declare module.exports: $Exports<'react-google-maps-loader/lib/index'>;
}
declare module 'react-google-maps-loader/lib/loadGoogleMapsSdk/index.js' {
  declare module.exports: $Exports<'react-google-maps-loader/lib/loadGoogleMapsSdk/index'>;
}
declare module 'react-google-maps-loader/umd/react-google-maps-loader.js' {
  declare module.exports: $Exports<'react-google-maps-loader/umd/react-google-maps-loader'>;
}
