// flow-typed signature: 61f0b04f65a59cfa02db2d02be933c8d
// flow-typed version: <<STUB>>/redux-saga-routines_v^2.2.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga-routines'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga-routines' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga-routines/dist/bindPromiseCreators' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/dist/bindRoutineToReduxForm' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/dist/constants' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/dist/createRoutine' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/dist/index' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/dist/promisifyRoutine' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/dist/routinePromiseWatcherSaga' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/dist/routineStages' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/es/bindPromiseCreators' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/es/bindRoutineToReduxForm' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/es/constants' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/es/createRoutine' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/es/index' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/es/promisifyRoutine' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/es/routinePromiseWatcherSaga' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/es/routineStages' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/src/bindPromiseCreators' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/src/bindRoutineToReduxForm' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/src/constants' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/src/createRoutine' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/src/index' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/src/promisifyRoutine' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/src/routinePromiseWatcherSaga' {
  declare module.exports: any;
}

declare module 'redux-saga-routines/src/routineStages' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga-routines/dist/bindPromiseCreators.js' {
  declare module.exports: $Exports<'redux-saga-routines/dist/bindPromiseCreators'>;
}
declare module 'redux-saga-routines/dist/bindRoutineToReduxForm.js' {
  declare module.exports: $Exports<'redux-saga-routines/dist/bindRoutineToReduxForm'>;
}
declare module 'redux-saga-routines/dist/constants.js' {
  declare module.exports: $Exports<'redux-saga-routines/dist/constants'>;
}
declare module 'redux-saga-routines/dist/createRoutine.js' {
  declare module.exports: $Exports<'redux-saga-routines/dist/createRoutine'>;
}
declare module 'redux-saga-routines/dist/index.js' {
  declare module.exports: $Exports<'redux-saga-routines/dist/index'>;
}
declare module 'redux-saga-routines/dist/promisifyRoutine.js' {
  declare module.exports: $Exports<'redux-saga-routines/dist/promisifyRoutine'>;
}
declare module 'redux-saga-routines/dist/routinePromiseWatcherSaga.js' {
  declare module.exports: $Exports<'redux-saga-routines/dist/routinePromiseWatcherSaga'>;
}
declare module 'redux-saga-routines/dist/routineStages.js' {
  declare module.exports: $Exports<'redux-saga-routines/dist/routineStages'>;
}
declare module 'redux-saga-routines/es/bindPromiseCreators.js' {
  declare module.exports: $Exports<'redux-saga-routines/es/bindPromiseCreators'>;
}
declare module 'redux-saga-routines/es/bindRoutineToReduxForm.js' {
  declare module.exports: $Exports<'redux-saga-routines/es/bindRoutineToReduxForm'>;
}
declare module 'redux-saga-routines/es/constants.js' {
  declare module.exports: $Exports<'redux-saga-routines/es/constants'>;
}
declare module 'redux-saga-routines/es/createRoutine.js' {
  declare module.exports: $Exports<'redux-saga-routines/es/createRoutine'>;
}
declare module 'redux-saga-routines/es/index.js' {
  declare module.exports: $Exports<'redux-saga-routines/es/index'>;
}
declare module 'redux-saga-routines/es/promisifyRoutine.js' {
  declare module.exports: $Exports<'redux-saga-routines/es/promisifyRoutine'>;
}
declare module 'redux-saga-routines/es/routinePromiseWatcherSaga.js' {
  declare module.exports: $Exports<'redux-saga-routines/es/routinePromiseWatcherSaga'>;
}
declare module 'redux-saga-routines/es/routineStages.js' {
  declare module.exports: $Exports<'redux-saga-routines/es/routineStages'>;
}
declare module 'redux-saga-routines/src/bindPromiseCreators.js' {
  declare module.exports: $Exports<'redux-saga-routines/src/bindPromiseCreators'>;
}
declare module 'redux-saga-routines/src/bindRoutineToReduxForm.js' {
  declare module.exports: $Exports<'redux-saga-routines/src/bindRoutineToReduxForm'>;
}
declare module 'redux-saga-routines/src/constants.js' {
  declare module.exports: $Exports<'redux-saga-routines/src/constants'>;
}
declare module 'redux-saga-routines/src/createRoutine.js' {
  declare module.exports: $Exports<'redux-saga-routines/src/createRoutine'>;
}
declare module 'redux-saga-routines/src/index.js' {
  declare module.exports: $Exports<'redux-saga-routines/src/index'>;
}
declare module 'redux-saga-routines/src/promisifyRoutine.js' {
  declare module.exports: $Exports<'redux-saga-routines/src/promisifyRoutine'>;
}
declare module 'redux-saga-routines/src/routinePromiseWatcherSaga.js' {
  declare module.exports: $Exports<'redux-saga-routines/src/routinePromiseWatcherSaga'>;
}
declare module 'redux-saga-routines/src/routineStages.js' {
  declare module.exports: $Exports<'redux-saga-routines/src/routineStages'>;
}
