// flow-typed signature: a76828c9d8c74a1c5169dbcc7e5fc818
// flow-typed version: <<STUB>>/storybook-addon-specifications_v^2.1.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-specifications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-specifications' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-specifications/dist/components/Specifications/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/dist/components/Specifications/style' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/dist/containers/Specifications/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/dist/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/dist/manager' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/dist/preview' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-specifications/dist/components/Specifications/index.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/dist/components/Specifications/index'>;
}
declare module 'storybook-addon-specifications/dist/components/Specifications/style.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/dist/components/Specifications/style'>;
}
declare module 'storybook-addon-specifications/dist/containers/Specifications/index.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/dist/containers/Specifications/index'>;
}
declare module 'storybook-addon-specifications/dist/index.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/dist/index'>;
}
declare module 'storybook-addon-specifications/dist/manager.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/dist/manager'>;
}
declare module 'storybook-addon-specifications/dist/preview.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/dist/preview'>;
}
declare module 'storybook-addon-specifications/register.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/register'>;
}
