// flow-typed signature: fdf7cbe7c66b3d9bdd6382e06df24158
// flow-typed version: <<STUB>>/string.prototype.includes_v^1.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string.prototype.includes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string.prototype.includes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'string.prototype.includes/includes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'string.prototype.includes/includes.js' {
  declare module.exports: $Exports<'string.prototype.includes/includes'>;
}
