// flow-typed signature: 08c86fb998e14fe6dea09920ebf14145
// flow-typed version: <<STUB>>/@storybook/addon-backgrounds_v^3.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-backgrounds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-backgrounds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-backgrounds/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/__tests__/BackgroundPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/__tests__/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/__tests__/Swatch' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/BackgroundPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/index.story' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/Swatch' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/docs/static/manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/docs/static/preview.bundle' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-backgrounds/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/coverage/lcov-report/prettify'>;
}
declare module '@storybook/addon-backgrounds/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/coverage/lcov-report/sorter'>;
}
declare module '@storybook/addon-backgrounds/dist/__tests__/BackgroundPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/__tests__/BackgroundPanel'>;
}
declare module '@storybook/addon-backgrounds/dist/__tests__/index.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/__tests__/index'>;
}
declare module '@storybook/addon-backgrounds/dist/__tests__/Swatch.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/__tests__/Swatch'>;
}
declare module '@storybook/addon-backgrounds/dist/BackgroundPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/BackgroundPanel'>;
}
declare module '@storybook/addon-backgrounds/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/index'>;
}
declare module '@storybook/addon-backgrounds/dist/index.story.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/index.story'>;
}
declare module '@storybook/addon-backgrounds/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/register'>;
}
declare module '@storybook/addon-backgrounds/dist/Swatch.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/Swatch'>;
}
declare module '@storybook/addon-backgrounds/docs/static/manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/docs/static/manager.bundle'>;
}
declare module '@storybook/addon-backgrounds/docs/static/preview.bundle.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/docs/static/preview.bundle'>;
}
declare module '@storybook/addon-backgrounds/register.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/register'>;
}
